services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company_info_bot
    env_file:
      - .env
    environment:
      - PARSER_API_URL=http://company_parser_api:5050
    volumes:
      - ./logs:/app/logs
      - ./bot_data.db:/app/bot_data.db
    networks:
      - parser-net
    restart: unless-stopped

networks:
  parser-net:
    external: true